---
title: "About"
date: "2014-04-09"
layout: "about"
menu: "main"
weight: 40
---
This is my personal blog where I write about data science projects focussing on music. The blog was build in R using [blogdown](https://github.com/rstudio/blogdown), which provides an easy way to host static websites based on R markdown and Hugo. The website uses the [Hugo Nuo Theme](https://themes.gohugo.io/hugo-nuo/) and is hosted on GitHub.

# About me
I am a Postdoctoral researcher, who applies data science & psychology tools to learn about people’s behavior.
Currently I work at Goldsmiths, University of London and the University of Hamburg. Previously I was a research fellow at the Max Planck Institute for Empirical Aesthetics and a visiting researcher at the University of Oxford.

You can find most of my publications on [ResearchGate](https://www.researchgate.net/profile/Paul_Elvers) and read more about me on [LinkedIn](https://www.linkedin.com/in/paul-elvers/). 

Feel free to get in touch: p.h.elvers at gmail dot com











