---
title: "Publications"
date: "2014-04-09"
layout: "about"
menu: "main"
weight: 40
---
Elvers, P., & Steffens, J. [(2017)](https://www.frontiersin.org/articles/10.3389/fpsyg.2017.02026/full). The Sound of Success: Investigating Cognitive and Behavioral Effects of Motivational Music in Sports. *Frontiers in Psychology*, *8*(2026).

Elvers, P., Fischinger, T., & Steffens, J. [(2017)](http://journals.sagepub.com/doi/abs/10.1177/0305735617707354). Music listening as self-enhancement: Effects of empowering music on explicit and implicit momentary self-esteem. *Psychology of Music*, *46*(3), 307 - 325.

Elvers, P. [(2016)](https://www.frontiersin.org/articles/10.3389/fpsyg.2016.00002/full). Songs for the Ego: Theorizing Musical Self-Enhancement. *Frontiers in Psychology*, *7*(2).

Greb, F., Elvers, P., & Fischinger, T. [(2016)](http://journals.sagepub.com/doi/abs/10.1177/0276237415625258). Trends in Empirical Aesthetics: A Review of the Journal "Empirical Studies of the Arts" from 1983 to 2014. *Empirical Studies of the Arts*, *35*(1), 3 - 26.

Elvers, P., Omigie, D., Fuhrmann, W., & Fischinger, T. [(2015)](https://www.frontiersin.org/articles/10.3389/fpsyg.2015.01252/full). Exploring the musical taste of expert listeners: musicology students reveal tendency toward omnivorous taste. *Frontiers in Psychology*, *6*(1252).